#!/bin/bash

echo "                                                                       "
echo -e "\e[34m                                                              "
echo "         ████████╗ ██████╗   █████╗   ██████╗ ███████╗ ███████╗        "
echo "         ╚══██╔══╝ ██╔══██╗ ██╔══██╗ ██╔════╝ ██╔════╝ ██╔════╝        "
echo "            ██║    ██████╔╝ ███████║ ██║      █████╗   ███████╗        "
echo "            ██║    ██╔══██╗ ██╔══██║ ██║      ██╔══╝   ╚════██║        "
echo "            ██║    ██║  ██║ ██║  ██║ ╚██████╗ ███████╗ ███████║        "
echo "            ╚═╝    ╚═╝  ╚═╝ ╚═╝  ╚═╝  ╚═════╝ ╚══════╝ ╚══════╝        "
echo "                                                                       "
echo "                             P I P E L I N E                           "
echo "                                                                       "
echo -e "    \e[32m      |  A hybrid pipeline for reconstruction & analysis  | \e[0m" 
echo -e "    \e[32m      |  of viral and host genomes at multi-organ level.  | \e[0m"
echo "                                                                "
echo -e "\e[93m    Usage: ./TRACESPipe.sh [options]                     \e[0m"
echo "                                                                       "
echo -e "\e[34m ===========            GENERAL OPTIONS              ==========\e[0m"
echo "                                                                       "
echo "    -h,     --help            Show this help message and exit,         "
echo "    -v,     --version         Show the version and some information,   "
echo "    -flog,  --flush-logs      Flush logs (delete logs),                "
echo "    -fout,  --flush-output    Flush output data (delete all output_data), "
echo "    -t <THREADS>, --threads <THREADS> Number of threads to use,        "
echo "                                                                       "
echo -e "\e[34m ===========            SETUP COMMANDS               ==========\e[0m"
echo "                                                                       "
echo "    -i,     --install         Installation of all the tools,           "
echo "    -up,    --update          Update all the tools in TRACESPipe,      "
echo "    -spv,   --show-prog-ver   Show included programs versions,         "
echo "                                                                       "
echo "    -st,    --sample          Creates human ref. VDB and sample organ, "
echo "                                                                       "
echo "    -gmt,   --get-max-threads Get the number of maximum machine threads,"
echo "                                                                       "
echo "    -dec,   --decrypt         Decrypt (all files in ../encrypted_data), "
echo "    -enc,   --encrypt         Encrypt (all files in ../to_encrypt_data),"
echo "                                                                       "
echo "    -vdb,   --build-viral     Build viral database (all) [Recommended], "
echo "    -vdbr,  --build-viral-r   Build viral database (references only),  "
echo "    -udb,   --build-unviral   Build non viral database (control),      "
echo "    -lcm,   --lcr-mask-vdb    Construct an LCR masked viral database   "
echo "                              Uses alt-vdb if specified                "
echo "                                                                       "
echo "    -afs <FASTA>, --add-fasta <FASTA>                                  "
echo "                              Add a FASTA sequence to the viral database,"
echo "    -aes <ID>, --add-extra-seq <ID>                                    "
echo "                              Add extra sequence to the viral database,"
echo "    -gx,    --get-extra-vir   Downloads/appends (VDB) extra viral seq, "
echo "                                                                       "
echo "    -gad,   --gen-adapters    Generate FASTA file with adapters,       "
echo "    -gp,    --get-phix        Extracts PhiX genomes (Needs viral DB),  "
echo "    -gm,    --get-mito        Downloads human Mitochondrial genome,    "
echo "                                                                       "
echo "    -dwms,  --download-mito-species                                    "
echo "                              Downloads the complete NCBI mitogenomes  "
echo "                              database containing the existing species,"
echo "                                                                       "
echo "    -dwmp,  --download-mito-population                                 "
echo "                              Downloads two complete mitogenome databases"
echo "                              with healthy and pathogenic sequences,   "
echo "                                                                       "
echo "    -aums,  --auth-mito-species                                        "
echo "                              Autheticate the mitogenome species,      "
echo "                                                                       "
echo "    -aump,  --auth-mito-population                                     "
echo "                              Authenticate closest population,         "
echo "                                                                       "
echo "    -cmt <ID>, --change-mito <ID>                                      "
echo "                              Set any Mitochondrial genome by ID,      "
echo "                                                                       "
echo "    -gy,    --get-y-chromo    Downloads human Y-chromosome,            "
echo "    -gax,   --get-all-aux     Runs -gad -gp -gm -gy,                   "
echo "                                                                       "
echo "    -cbn,   --create-blast-db It creates a nucleotide blast database,  "
echo "    -ubn,   --update-blast-db It updates a nucleotide blast database,  "
echo "                                                                       "
echo -e "\e[34m ===========           ANALYSIS COMMANDS             ==========\e[0m"
echo "                                                                       "
echo "    --- Some commands can only be run with or after others.            "
echo "        At the bottom of this section is a dependency tree             "
echo "                                                                       "
echo "    -ra,    --run-analysis    Run data analysis (core),                      "
echo "    -all,   --run-all         Run all the options (excluding the specific).  "
echo "    -proc,  --run-preprocess  Run adapter removal, quality trimming,   "
echo "                              length filtering, base correction,       "
echo "                              and poly-g tail removal with fastp       "
echo "                                                                       "
echo "    -sfs <FASTA>, --search-blast-db <FASTA>                            "
echo "                              It blasts the nucleotide (nt) blast DB,  "
echo "    -sfrs <FASTA>, --search-blast-remote-db <FASTA>                    "
echo "                              It blasts remotly thenucleotide (nt) blast "
echo "                              database (it requires internet connection), "
echo "                                                                       "
echo "    -gbb,   --best-of-bests   Identifies the best of bests references  "
echo "                              between multiple organs [similar reference], "
echo "                                                                       "
echo "    -rm,    --run-meta        Run viral metagenomic identification,    "
echo "    -ro,    --run-meta-nv     Run NON-viral metagenomic identification,"
echo "    -rpro,  --run-profiles    Run complexity and relative profiles (control), "
echo "                                                                       "
echo "    -rpgi <ID>,  --run-gid-complexity-profile <ID>                     "
echo "                              Run complexity profiles by GID,          "
echo "                                                                       "
echo "    -rava,  --run-all-v-alig  Run all viral align/sort/consensus seqs  "
echo "                              from a specific list,                    "
echo "                                                                       "
echo "    -rsr <ID>, --run-specific <ID/PATTERN>                             "
echo "                              Run specific reference align/consensus,  "
echo "                                                                       "
echo "    -rsx <ID>, --run-extreme <ID/PATTERN>                              "
echo "                              Run specific reference align/consensus   "
echo "                              using extreme sensitivity;               "
echo "                              Retained for backwards compatibility;    "
echo "                              Now an alias for -vhs -rsr <ID/PATTERN>, "
echo "                                                                       "
echo "    -rmt,   --run-mito        Run Mito align and consensus seq,        "
echo "    -rmtd,  --run-mito-dam    Run Mito damage only,                    "
echo "                                                                       "
echo "    -rgid <ID>, --run-gid-damage <ID>                                  "
echo "                              Run damage pattern analysis by GID,      "
echo "                                                                       "
echo "    -rya,   --run-cy-align    Run CY align and consensus seq,          "
echo "    -ryq,   --run-cy-quant    Estimate the quantity of CY DNA,         "
echo "                                                                       "
echo "    -rda,   --run-de-novo     Run de-novo assembly,                    "
echo "                                                                       "
echo "    -rhyb,  --run-hybrid      Run hybrid assembly (align/de-novo),     "
echo "    -rsd <ID>, --run-de-novo-specific <ID/PATTERN>                     "
echo "                              Run specific alignments of the de-novo   "
echo "                              to the reference genome,                 "
echo "                                                                       "
echo "    -cast,  --compile-aln-stats <TYPE>                                 "
echo "                              Combine breadth, depth, similarity,      "
echo "                              and selected mapping statistics into a   "
echo "                              report. Valid types are: viral, mtdna    "
echo "                              cy, specific, and all. Auto-enabled      "
echo "                              with any alignment command.              "
echo "    -rmhc,  --run-multiorgan-consensus                                 "
echo "                              Run alignments/consensus between all the "
echo "                              reconstructed organ sequences,           "
echo "                                                                       "
echo "    -vis,   --visual-align    Run Visualization tool for alignments,   "
echo "    -covl,  --coverage-latex  Run coverage table in Latex format,      "
echo "    -covc,  --coverage-csv    Run coverage table in CSV format,        "
echo "                                                                       "
echo "    -covp <NAME>,  --coverage-profile <BED_NAME_FILE>                   "
echo "                              Run coverage profile for specific BED file, "
echo "                                                                       "
echo "    -diff,  --run-diff        Run diff -> reference and hybrid (ident/SNPs), "
echo "                                                                       "
echo "    -sdiff <V_NAME> <ID/PATTERN>, --run-specific-diff <V_NAME> <ID/PATTERN>  "
echo "                              Run specific diff of reconstructed to a virus  "
echo "                              pattern of ID. Example: -sdiff B19 AY386330.1, "
echo "                                                                       "
echo "    -brec,  --blast-reconstructed                                      "
echo "                              Run local blast over reconstructed genomes, "
echo "                                                                             "
echo "                                                                       "
echo "    --- Dependency Tree ---                                            "
echo "                                                                       "
echo "    run-preprocess                                                     "
echo "    ├───run-meta                                                       "
echo "    │   ├───run-profiles                                               "
echo "    │   └───run-all-v-alig                                             "
echo "    │       ├───compile-aln-stats viral                                "
echo "    │       ├───coverage-latex                                         "
echo "    │       ├───coverage-csv                                           "
echo "    │       └───run-diff                                               "
echo "    ├───run-specific                                                   "
echo "    │   └───compile-aln-stats specific                                 "
echo "    ├───run-mito                                                       "
echo "    │   └───compile-aln-stats mtdna                                    "
echo "    ├───run-cy-align                                                   "
echo "    │   └───compile-aln-stats cy                                       "
echo "    ├───run-cy-quant                                                   "
echo "    └───run-de-novo                                                    "
echo "        ├───run-hybrid                                                 "
echo "        │   ├───run-multiorgan-consensus                               "
echo "        │   ├───run-diff                                               "
echo "        │   ├───run-specific-diff                                      "
echo "        │   └───blast-reconstructed                                    "
echo "        └───run-de-novo-specific                                       "
echo "    search-blast-db                                                    "
echo "    search-blast-remote-db                                             "
echo "    best-of-bests                                                      "
echo "    run-gid-complexity-profile                                         "
echo "    run-mito-dam                                                       "
echo "    run-gid-damage                                                     "
echo "    visual-align                                                       "
echo "    coverage-profile                                                   "
echo "                                                                       "
echo -e "\e[34m ===========           ANALYSIS OPTIONS              ==========\e[0m"
echo "                                                                       "
echo "    -avdb <FASTA>, --alt-viral-db <FASTA>                              "
echo "                              Specify a path to fasta file containing  "
echo "                               viral sequences                         "
echo "                              Sequence names must include the accession"
echo "                               as the first field, either whitespace or"
echo "                               underscore (_) delimited (NC_ handled)  "
echo "    -vdbm <PATH>, --viral-db-metadata <PATH>                           "
echo "                              Specify a path to a tab del file which   "
echo "                               has sequence GID/ACC in the first column"
echo "                               and a Name representing a virus label   "
echo "                               in the second                           "
echo "                              This changes the meta-analysis behaviour:"
echo "                               rather than using internal virus names  "
echo "                               and inclusion criteria, the relationships"
echo "                               defined in the provided file are used.  "
echo "                              This allows the user to define groupings "
echo "                               of interest in the default, or user     "
echo "                               provided viral database.                "
echo "                                                                       "
echo "    -rdup,  --remove-dup      Remove duplications (e.g. PCR dup),      "
echo "    -vhs,   --very-sensitive  Aligns with very high sensitivity (slower),  "
echo "                                                                       "
echo "    -adr,   --attempt-denovo-restart                                   "
echo "                              TRACESPipe will attempt to run previous  "
echo "                              de-novo assemblies from their last       "
echo "                              checkpoint, useful if an external fault  "
echo "                              halted assembly                          "
echo "                              Warning: If resuming initiates but later "
echo "                              fails, assembly will restart from scratch"
echo "    -dmef <VALUE>,  --denovo-mem-estimate-factor <VALUE>     Default:50"
echo "                              A value multiplied by the file size of   "
echo "                              compressed raw foward reads to estimate  "
echo "                              the spades memory usage. Controls trigger"
echo "                              for bbnorm digital normalization.        "
echo "                              A value of 0 disables bbnorm.            "
echo "    -mdm,   --max-denovo-mem                                Default:350"
echo "                              Maximum memory in GB to allocate for     "
echo "                              de novo assemly. A value of 0 removes the"
echo "                              limit and disables bbnorm.               "
echo "                                                                       "
echo "    -ulcm, --use-lcr-masked-vdb                                                                   "
echo "                              Use the pre-constructed lcr masked vdb   "
echo "                              for input to FALCON; disabled unless -lcm"
echo "                              has been run                             "
echo "    -pdep <FILE>, --pattern-depletion <FILE>                           "
echo "                              A path to a file containing regular      "
echo "                              expressions. Matches are filtered out    "
echo "                              of FALCON input. Primary use is to filter"
echo "                              patterns which exist in both a virus and "
echo "                              background sequences (eq. telomeres)     "
echo "    -iss <SIZE>, --inter-sim-size <SIZE>                               "
echo "                              Inter-genome similarity top size (control), "
echo "                                                                       "
echo "    -cpwi <VALUE>, --complexity-profile-window <VALUE>                 "
echo "                              Complexity profile window size,          "
echo "    -cple <VALUE>, --complexity-profile-level <VALUE>                  "
echo "                              Complexity profile compression level [1;10], "
echo "                                                                       "
echo "    -mis <VALUE>, --min-similarity <VALUE>                             "
echo "                              Minimum similarity value to consider the "
echo "                              sequence for alignment-consensus (filter), "
echo "                                                                       "
echo "    -misl <VALUE>, --min-similarity-len <VALUE>                        "
echo "                              Minimum product of similarity value and  "
echo "                              best hit sequence length for             "
echo "                              alignment-consensus (filter),            "
echo "    -misv <PATH>, --min-similarity-virus <PATH>                        "
echo "                              Path to a tab sep file with tow columns  "
echo "                              containing the virus and min sim values  "
echo "                              Any values lower than --misl are ignored "
echo "                                                                       "
echo "    -top <VALUE>, --view-top <VALUE>                                   "
echo "                              Display the top <VALUE> with the highest "
echo "                              similarity (by descending order),        "
echo "    -amax <VALUE>, --max-alignments <VALUE>                            "
echo "                              The maximum number of alignments to      "
echo "                              report for any one read; 0 = no limit,   "
echo "                                                                       "
echo "    -c <VALUE>,   --cache <VALUE>                                      "
echo "                              Cache to be used by FALCON-meta,         "
echo "    -tsv <VALUE>,   --top-size-virus <VALUE>                           "
echo "                              Top size to be used by FALCON-meta when  "
echo "                              using TRACES_metagenomic_viral.sh;       "
echo "                              default:0 -> seq count in viral db       "
echo "    -ts <VALUE>,   --top-size <VALUE>                                  "
echo "                              Top size to be used by FALCON-meta when  "
echo "                              using TRACES_metagenomic.sh;             "
echo "                              default:0 -> seq count in  non-viral db  "
echo "                                                                       "
echo "    -cmax <MAX>,   --max-coverage <MAX_COVERAGE>                       "
echo "                              Maximum depth coverage (depth normalization), "
echo "    -clog <VALUE>, --coverage-log-scale <VALUE>                        "
echo "                              Coverage profile logarithmic scale VALUE=Base, "
echo "    -cwis <VALUE>, --coverage-window-size <VALUE>                      "
echo "                              Coverage window size for low-pass filter, "
echo "    -cdro <VALUE>, --coverage-drop <VALUE>                             "
echo "                              Coverage drop size (sampling),           "
echo "    -covm <VALUE>, --coverage-min-x <VALUE>                             "
echo "                              Coverage minimum value for x-axis        "
echo "                                                                       "
echo -e "\e[34m ===========                EXAMPLES                 ==========\e[0m"
echo "                                                                       "
echo -e "\e[93m    Ex: ./TRACESPipe.sh --flush-output --flush-logs --run-mito --run-meta \e[0m"
echo -e "\e[93m    --remove-dup --run-de-novo --run-hybrid --min-similarity 1 --run-diff \e[0m" 
echo -e "\e[93m    --very-sensitive --best-of-bests --run-multiorgan-consensus \e[0m"
echo "                                                                       "
echo "    Add the file meta_info.txt at ../meta_data/ folder. Example:       "
echo "    meta_info.txt -> 'organ:reads_forward.fa.gz:reads_reverse.fa.gz'   "
echo "    The reads must be GZIPed in the ../input_data/ folder.             "
echo "    The output results are at ../output_data/ folder.                  "
echo "                                                                       "
echo -e "\e[32m    Contact: tracespipe@gmail.com                        \e[0m"
echo "                                                                       "
